name: cloudflare preview

on:
  pull_request:
    paths:
      - "cloudflare/**"
      - ".github/workflows/cloudflare-preview.yml"
  push:
    branches: [main]
    paths:
      - "cloudflare/**"
      - ".github/workflows/cloudflare-preview.yml"

jobs:
  preview:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: cloudflare/go.mod
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: dev
          work-dir: cloudflare
          cloud-url: file://~
